INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Spittal an der Drau','Austria','Austria','2586'),
  ('Hard','Austria','Austria','2521'),
  ('Stockerau','Austria','Austria','3547'),
  ('Schwechat','Austria','Austria','7260'),
  ('Weiz','Austria','Austria','4783'),
  ('Leoben','Austria','Austria','5401'),
  ('Klagenfurt','Austria','Austria','8034'),
  ('Weiz','Austria','Austria','4177'),
  ('Vienna','Austria','Austria','8757'),
  ('Bischofshofen','Austria','Austria','3126'),
  ('Vienna','Austria','Austria','8849'),
  ('Ried im Innkreis','Austria','Austria','2784'),
  ('Waidhofen an der Ybbs','Austria','Austria','7063'),
  ('Imst','Austria','Austria','6226'),
  ('Vienna','Austria','Austria','7225'),
  ('NeudÃ¶rfl','Austria','Austria','2703'),
  ('WÃ¶rgl','Austria','Austria','5562'),
  ('Amstetten','Austria','Austria','6917'),
  ('Innsbruck','Austria','Austria','9855'),
  ('Gols','Austria','Austria','1567'),
  ('Salzburg','Austria','Austria','4619'),
  ('Sankt Johann im Pongau','Austria','Austria','9816'),
  ('Vienna','Austria','Austria','6721'),
  ('Vienna','Austria','Austria','8171'),
  ('Frauenkirchen','Austria','Austria','6135'),
  ('VÃ¶cklabruck','Austria','Austria','6925'),
  ('Bad Ischl','Austria','Austria','2680'),
  ('Vienna','Austria','Austria','6284'),
  ('Bad Ischl','Austria','Austria','6364'),
  ('Brunn am Gebirge','Austria','Austria','6354'),
  ('Hohenems','Austria','Austria','5702'),
  ('Feldkirchen in KÃ¤rnten','Austria','Austria','5758'),
  ('Vienna','Austria','Austria','8321'),
  ('Bischofshofen','Austria','Austria','2233'),
  ('Wolfurt','Austria','Austria','8432'),
  ('Vienna','Austria','Austria','2575'),
  ('Innsbruck','Austria','Austria','9888'),
  ('Sankt Johann im Pongau','Austria','Austria','9675'),
  ('Wals-Siezenheim','Austria','Austria','8138'),
  ('KÃ¶flach','Austria','Austria','2828'),
  ('Rechnitz','Austria','Austria','8841'),
  ('Telfs','Austria','Austria','3867'),
  ('Salzburg','Austria','Austria','3484'),
  ('Rum','Austria','Austria','3345'),
  ('Parndorf','Austria','Austria','3311'),
  ('Lauterach','Austria','Austria','3286'),
  ('VÃ¶lkermarkt','Austria','Austria','3518'),
  ('Saalfelden am Steinernen Meer','Austria','Austria','9459'),
  ('Traiskirchen','Austria','Austria','5591'),
  ('Schwaz','Austria','Austria','6351');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Stockerau','Austria','Austria','8081'),
  ('Leonding','Austria','Austria','6268'),
  ('Hollabrunn','Austria','Austria','3602'),
  ('St. Veit an der Glan','Austria','Austria','6498'),
  ('Wolfsberg','Austria','Austria','6742'),
  ('Bruckneudorf','Austria','Austria','8542'),
  ('Klosterneuburg','Austria','Austria','1802'),
  ('Lauterach','Austria','Austria','7908'),
  ('Wals-Siezenheim','Austria','Austria','1458'),
  ('Wolfurt','Austria','Austria','5886'),
  ('Hallein','Austria','Austria','4885'),
  ('Voitsberg','Austria','Austria','5118'),
  ('Altach','Austria','Austria','4741'),
  ('Landeck','Austria','Austria','6354'),
  ('Leonding','Austria','Austria','8983'),
  ('Telfs','Austria','Austria','7455'),
  ('Leoben','Austria','Austria','9764'),
  ('Feldkirchen in KÃ¤rnten','Austria','Austria','4127'),
  ('Vienna','Austria','Austria','2130'),
  ('Vienna','Austria','Austria','5675'),
  ('Braunau am Inn','Austria','Austria','3257'),
  ('Ferlach','Austria','Austria','7298'),
  ('GroÃŸpetersdorf','Austria','Austria','1239'),
  ('Salzburg','Austria','Austria','3015'),
  ('Hohenems','Austria','Austria','5515'),
  ('Velden am WÃ¶rther See','Austria','Austria','7548'),
  ('Korneuburg','Austria','Austria','4270'),
  ('Sankt Johann im Pongau','Austria','Austria','2243'),
  ('Vienna','Austria','Austria','8038'),
  ('Marchtrenk','Austria','Austria','3217'),
  ('Vienna','Austria','Austria','3376'),
  ('Parndorf','Austria','Austria','6381'),
  ('Wolfsberg','Austria','Austria','9738'),
  ('St. Veit an der Glan','Austria','Austria','3449'),
  ('Vienna','Austria','Austria','8137'),
  ('Leonding','Austria','Austria','6953'),
  ('Perchtoldsdorf','Austria','Austria','7892'),
  ('Neunkirchen','Austria','Austria','5851'),
  ('Ebenthal in KÃ¤rnten','Austria','Austria','4821'),
  ('Ferlach','Austria','Austria','3133'),
  ('WÃ¶rgl','Austria','Austria','8482'),
  ('Wals-Siezenheim','Austria','Austria','1739'),
  ('Eisenstadt','Austria','Austria','4643'),
  ('Gmunden','Austria','Austria','7019'),
  ('AltmÃ¼nster','Austria','Austria','2881'),
  ('Mattersburg','Austria','Austria','6425'),
  ('Velden am WÃ¶rther See','Austria','Austria','1838'),
  ('Hallein','Austria','Austria','2421'),
  ('St. Veit an der Glan','Austria','Austria','7545'),
  ('Wolfsberg','Austria','Austria','7878');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Graz','Austria','Austria','5867'),
  ('Hohenems','Austria','Austria','2380'),
  ('Sankt Johann im Pongau','Austria','Austria','7339'),
  ('Graz','Austria','Austria','3645'),
  ('St. PÃ¶lten','Austria','Austria','8848'),
  ('Landeck','Austria','Austria','3255'),
  ('KÃ¶flach','Austria','Austria','6665'),
  ('Enns','Austria','Austria','8144'),
  ('Hall in Tirol','Austria','Austria','6608'),
  ('Vienna','Austria','Austria','4278'),
  ('Marchtrenk','Austria','Austria','4347'),
  ('Klagenfurt','Austria','Austria','5576'),
  ('Knittelfeld','Austria','Austria','3950'),
  ('Leoben','Austria','Austria','1790'),
  ('Wels','Austria','Austria','6620'),
  ('Brunn am Gebirge','Austria','Austria','7533'),
  ('Spittal an der Drau','Austria','Austria','3852'),
  ('Ebenthal in KÃ¤rnten','Austria','Austria','7233'),
  ('Ebenthal in KÃ¤rnten','Austria','Austria','4793'),
  ('Tulln an der Donau','Austria','Austria','6334'),
  ('Vienna','Austria','Austria','4503'),
  ('AltmÃ¼nster','Austria','Austria','5897'),
  ('Bregenz','Austria','Austria','6484'),
  ('Ferlach','Austria','Austria','9366'),
  ('NeudÃ¶rfl','Austria','Austria','3674'),
  ('AltmÃ¼nster','Austria','Austria','9545'),
  ('Forchtenstein','Austria','Austria','2312'),
  ('Wals-Siezenheim','Austria','Austria','1547'),
  ('Vienna','Austria','Austria','9183'),
  ('Bludenz','Austria','Austria','8361'),
  ('Schwaz','Austria','Austria','3116'),
  ('Wals-Siezenheim','Austria','Austria','9355'),
  ('Marchtrenk','Austria','Austria','3313'),
  ('Zirl','Austria','Austria','3112'),
  ('Finkenstein am Faaker See','Austria','Austria','5322'),
  ('Rankweil','Austria','Austria','9530'),
  ('Kapfenberg','Austria','Austria','3846'),
  ('Eisenstadt','Austria','Austria','7529'),
  ('Korneuburg','Austria','Austria','2433'),
  ('Steyr','Austria','Austria','7077'),
  ('Hollabrunn','Austria','Austria','1968'),
  ('Vienna','Austria','Austria','5576'),
  ('Spittal an der Drau','Austria','Austria','6522'),
  ('Velden am WÃ¶rther See','Austria','Austria','6802'),
  ('KÃ¶flach','Austria','Austria','6671'),
  ('Hall in Tirol','Austria','Austria','3365'),
  ('Amstetten','Austria','Austria','3351'),
  ('Voitsberg','Austria','Austria','6706'),
  ('Vienna','Austria','Austria','7611'),
  ('Weiz','Austria','Austria','6591');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Dornbirn','Austria','Austria','2566'),
  ('Leoben','Austria','Austria','8565'),
  ('Imst','Austria','Austria','8215'),
  ('Amstetten','Austria','Austria','4813'),
  ('Vienna','Austria','Austria','2846'),
  ('Ansfelden','Austria','Austria','5198'),
  ('Wolfurt','Austria','Austria','3555'),
  ('Vienna','Austria','Austria','4856'),
  ('GroÃŸpetersdorf','Austria','Austria','8967'),
  ('Wals-Siezenheim','Austria','Austria','1142'),
  ('Salzburg','Austria','Austria','7244'),
  ('Wals-Siezenheim','Austria','Austria','2106'),
  ('Bischofshofen','Austria','Austria','4768'),
  ('Parndorf','Austria','Austria','6111'),
  ('Sierning','Austria','Austria','5112'),
  ('Traun','Austria','Austria','4713'),
  ('Bludenz','Austria','Austria','7149'),
  ('Leoben','Austria','Austria','8360'),
  ('Vienna','Austria','Austria','4423'),
  ('Vienna','Austria','Austria','9984'),
  ('Hohenems','Austria','Austria','2544'),
  ('GÃ¼ssing','Austria','Austria','5376'),
  ('Vienna','Austria','Austria','4319'),
  ('Vienna','Austria','Austria','6619'),
  ('Klagenfurt','Austria','Austria','8611'),
  ('Linz','Austria','Austria','1244'),
  ('Hard','Austria','Austria','6294'),
  ('Vienna','Austria','Austria','3987'),
  ('Landeck','Austria','Austria','7297'),
  ('Rum','Austria','Austria','3161'),
  ('Deutschkreutz','Austria','Austria','1226'),
  ('Sankt Johann im Pongau','Austria','Austria','8560'),
  ('Lienz','Austria','Austria','5878'),
  ('Spittal an der Drau','Austria','Austria','5539'),
  ('Amstetten','Austria','Austria','7445'),
  ('Zwettl-NiederÃ¶sterreich','Austria','Austria','6056'),
  ('Ferlach','Austria','Austria','7152'),
  ('GÃ¼ssing','Austria','Austria','9147'),
  ('Neunkirchen','Austria','Austria','7028'),
  ('Vienna','Austria','Austria','3535'),
  ('Hohenems','Austria','Austria','2846'),
  ('Feldkirchen in KÃ¤rnten','Austria','Austria','3254'),
  ('KÃ¶flach','Austria','Austria','2979'),
  ('Hard','Austria','Austria','7489'),
  ('Marchtrenk','Austria','Austria','7387'),
  ('Knittelfeld','Austria','Austria','1072'),
  ('Rechnitz','Austria','Austria','3668'),
  ('Gmunden','Austria','Austria','2816'),
  ('PÃ¶ttsching','Austria','Austria','7965'),
  ('Kapfenberg','Austria','Austria','5825');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Knittelfeld','Austria','Austria','8441'),
  ('Weiz','Austria','Austria','5568'),
  ('Telfs','Austria','Austria','2726'),
  ('MÃ¶dling','Austria','Austria','6670'),
  ('St. PÃ¶lten','Austria','Austria','2668'),
  ('Ansfelden','Austria','Austria','8071'),
  ('Hohenems','Austria','Austria','5421'),
  ('Kufstein','Austria','Austria','8814'),
  ('Tulln an der Donau','Austria','Austria','3630'),
  ('Vienna','Austria','Austria','8786'),
  ('Vienna','Austria','Austria','6379'),
  ('Lustenau','Austria','Austria','1676');

INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Ludwigsburg','Germany','Germany','58151'),
  ('Melle','Germany','Germany','76741'),
  ('Erlangen','Germany','Germany','15283'),
  ('Itzehoe','Germany','Germany','00661'),
  ('LÃ¶rrach','Germany','Germany','43020'),
  ('Neuss','Germany','Germany','01218'),
  ('Heide','Germany','Germany','67811'),
  ('Blieskastel','Germany','Germany','77718'),
  ('DÃ¼sseldorf','Germany','Germany','34313'),
  ('Peine','Germany','Germany','27375'),
  ('Bautzen','Germany','Germany','04795'),
  ('Bremen','Germany','Germany','81329'),
  ('Spremberg','Germany','Germany','53865'),
  ('Heide','Germany','Germany','97744'),
  ('Flensburg','Germany','Germany','03235'),
  ('Bergen','Germany','Germany','49147'),
  ('Bremen','Germany','Germany','42136'),
  ('Heidenheim','Germany','Germany','19820'),
  ('Falkensee','Germany','Germany','59111'),
  ('Neustrelitz','Germany','Germany','40672'),
  ('Berlin','Germany','Germany','68452'),
  ('Bad Nauheim','Germany','Germany','37223'),
  ('Speyer','Germany','Germany','51744'),
  ('Berlin','Germany','Germany','83347'),
  ('Hamburg','Germany','Germany','31445'),
  ('Oberhausen','Germany','Germany','75494'),
  ('Hamburg','Germany','Germany','15344'),
  ('Falkensee','Germany','Germany','53728'),
  ('Eberswalde-Finow','Germany','Germany','56109'),
  ('Hamburg','Germany','Germany','72211'),
  ('Hamburg','Germany','Germany','62826'),
  ('Geesthacht','Germany','Germany','71154'),
  ('Naumburg','Germany','Germany','70174'),
  ('Baden-Baden','Germany','Germany','38586'),
  ('Andernach','Germany','Germany','73714'),
  ('Blieskastel','Germany','Germany','21778'),
  ('Hameln','Germany','Germany','52784'),
  ('Grimma','Germany','Germany','31725'),
  ('Sulzbach','Germany','Germany','55999'),
  ('Halberstadt','Germany','Germany','80208'),
  ('Wilhelmshaven','Germany','Germany','92774'),
  ('Bremerhaven','Germany','Germany','77478'),
  ('Geesthacht','Germany','Germany','36854'),
  ('Rostock','Germany','Germany','96535'),
  ('Andernach','Germany','Germany','10121'),
  ('Berlin','Germany','Germany','22468'),
  ('SaarbrÃ¼cken','Germany','Germany','44998'),
  ('Salzwedel','Germany','Germany','28376'),
  ('Berlin','Germany','Germany','41888'),
  ('Panketal','Germany','Germany','15615');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('Neuwied','Germany','Germany','21345'),
  ('SchwÃ¤bisch GmÃ¼nd','Germany','Germany','19637'),
  ('Homburg','Germany','Germany','72603'),
  ('Rendsburg','Germany','Germany','53682'),
  ('Ingelheim','Germany','Germany','70116'),
  ('Sangerhausen','Germany','Germany','76879'),
  ('Freising','Germany','Germany','12407'),
  ('Bremerhaven','Germany','Germany','84252'),
  ('Halberstadt','Germany','Germany','77533'),
  ('Elmshorn','Germany','Germany','87445'),
  ('Neustadt','Germany','Germany','80681'),
  ('Hof','Germany','Germany','32112'),
  ('GÃ¶rlitz','Germany','Germany','45456'),
  ('Oberhausen','Germany','Germany','27183'),
  ('MÃ¼nster','Germany','Germany','78130'),
  ('Hamburg','Germany','Germany','66030'),
  ('GÃ¶rlitz','Germany','Germany','48061'),
  ('Flensburg','Germany','Germany','58444'),
  ('Berlin','Germany','Germany','27712'),
  ('Emden','Germany','Germany','42658'),
  ('Rosenheim','Germany','Germany','23383'),
  ('Hof','Germany','Germany','67702'),
  ('Berlin','Germany','Germany','10027'),
  ('Bergisch Gladbach','Germany','Germany','51814'),
  ('Wadgassen','Germany','Germany','52543'),
  ('Griesheim','Germany','Germany','28651'),
  ('Hamburg','Germany','Germany','54766'),
  ('Celle','Germany','Germany','75922'),
  ('Rathenow','Germany','Germany','92663'),
  ('Esslingen','Germany','Germany','46908'),
  ('Ludwigsburg','Germany','Germany','32671'),
  ('Bexbach','Germany','Germany','38980'),
  ('Stralsund','Germany','Germany','67501'),
  ('GÃ¶ppingen','Germany','Germany','57554'),
  ('Aschaffenburg','Germany','Germany','08149'),
  ('Reinbek','Germany','Germany','88753'),
  ('Anklam','Germany','Germany','55553'),
  ('Elmshorn','Germany','Germany','43862'),
  ('Riesa','Germany','Germany','45858'),
  ('Quedlinburg','Germany','Germany','31171'),
  ('Bonn','Germany','Germany','75534'),
  ('Oldenburg','Germany','Germany','05297'),
  ('Rostock','Germany','Germany','28674'),
  ('PÃ¼ttlingen','Germany','Germany','03821'),
  ('Bremen','Germany','Germany','76282'),
  ('Quickborn','Germany','Germany','71265'),
  ('Bremen','Germany','Germany','58522'),
  ('Lampertheim','Germany','Germany','83147'),
  ('Hamburg','Germany','Germany','11426'),
  ('Bremerhaven','Germany','Germany','28521');
INSERT INTO CS_Schema.Location (City,State,Country,PostalCode)
VALUES
  ('NeumÃ¼nster','Germany','Germany','94492'),
  ('Bremerhaven','Germany','Germany','85853'),
  ('ZweibrÃ¼cken','Germany','Germany','16213'),
  ('Bremerhaven','Germany','Germany','20058'),
  ('Bremen','Germany','Germany','23718'),
  ('Rendsburg','Germany','Germany','69642'),
  ('Mainz','Germany','Germany','12483'),
  ('Senftenberg','Germany','Germany','85421'),
  ('Parchim	City','Germany','Germany','33523'),
  ('Elmshorn','Germany','Germany','07721'),
  ('Bad Neuenahr-Ahrweiler','Germany','Germany','86771'),
  ('Wedel','Germany','Germany','25313'),
  ('GÃ¶rlitz','Germany','Germany','84862'),
  ('Bad Kreuznach','Germany','Germany','80727'),
  ('Kleinmachnow','Germany','Germany','82232'),
  ('Anklam','Germany','Germany','83153'),
  ('Parchim	City','Germany','Germany','79641'),
  ('Blieskastel','Germany','Germany','05124'),
  ('Konstanz','Germany','Germany','24478'),
  ('Homburg','Germany','Germany','67532');
  
DELETE FROM CS_Schema.Location 
WHERE LocationID NOT IN (
	SELECT MIN(LocationID)
	FROM CS_Schema.Location
	GROUP BY City
)